Repository dkseoals15/sb01-hrbank-team04, pull requests merged in 2025-03, with the labels that each got.

#9 ✨ feat: 파일 관리 기능 개발
  src/main/java/com/codeit/sb01hrbankteam04/domain/file/controller/FileController.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/file/docs/FileControllerDocs.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/file/dto/FileDto.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/file/entity/File.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/file/entity/FileType.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/file/mapper/FileMapper.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/file/repository/FileRepository.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/file/service/FileService.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/file/service/FileServiceImpl.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/storage/FileStorage.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/storage/LocalFileStorage.java
  src/main/java/com/codeit/sb01hrbankteam04/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#11 ✨ feat: 서버에서 클라이언트 IP 자동 가져오기
  src/main/java/com/codeit/sb01hrbankteam04/global/util/ip/IPHeader.java
  src/main/java/com/codeit/sb01hrbankteam04/global/util/ip/IPUtils.java
  src/main/java/com/codeit/sb01hrbankteam04/global/util/ip/RequestIPContext.java
Labels: :sparkles: feat

#13 ✨ feat: 총 직원 수 기능 구현
  .gitignore
  src/main/java/com/codeit/sb01hrbankteam04/config/JpaAuditingConfig.java
  src/main/java/com/codeit/sb01hrbankteam04/config/PropertyConfig.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employee/controller/EmployeeController.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employee/entity/Employee.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employee/entity/EmployeeStatusType.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employee/repository/EmployeeRepository.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employee/service/EmployeeService.java
  src/main/java/com/codeit/sb01hrbankteam04/dto/employee/EmployeeCrateRequest.java
  src/main/java/com/codeit/sb01hrbankteam04/dto/employee/EmployeeDistributionResponse.java
  src/main/java/com/codeit/sb01hrbankteam04/dto/employee/EmployeeGroupResult.java
  src/main/java/com/codeit/sb01hrbankteam04/dto/employee/EmployeeResponse.java
  src/main/java/com/codeit/sb01hrbankteam04/dto/employee/EmployeeTrendResponse.java
  src/main/java/com/codeit/sb01hrbankteam04/dto/employee/EmployeeUpdateRequest.java
  src/main/java/com/codeit/sb01hrbankteam04/dto/employee/EmployeeUpdateResponse.java
  src/main/java/com/codeit/sb01hrbankteam04/dto/employee/EmployeesResponse.java
  src/main/java/com/codeit/sb01hrbankteam04/global/entity/BaseEntity.java
  src/main/java/org/example/sb01hrbankteam04/Sb01HrbankTeam04Application.java
  src/main/resources/application.properties
  src/test/java/com/codeit/sb01hrbankteam04/Sb01HrbankTeam04ApplicationTests.java
  src/test/java/com/codeit/sb01hrbankteam04/repository/employee/EmployeeRepositoryInitTest.java
  src/test/java/com/codeit/sb01hrbankteam04/service/EmployeeServiceDepartmentTest.java
  src/test/java/com/codeit/sb01hrbankteam04/service/EmployeeServiceGetEmployeeCountTest.java
  src/test/java/com/codeit/sb01hrbankteam04/service/EmployeeServicePositionTest.java
  src/test/java/com/codeit/sb01hrbankteam04/service/EmployeeServiceTrendTest.java
  src/test/java/org/example/sb01hrbankteam04/Sb01HrbankTeam04ApplicationTests.java
  src/test/resources/application.yml
Labels: :sparkles: feat

#16 ✨feat: 직원 정보 수정을 위한 엔티티 설정
  src/main/java/com/codeit/sb01hrbankteam04/Sb01HrbankTeam04Application.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employee/entity/Employee.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/audit/EmployeeRevisionListener.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/controller/EmployeeHistoryController.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/dto/request/ChangeLogRequest.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/dto/request/FilterRequest.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/dto/response/ChangeLogDto.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/dto/response/CursorPageResponseEmployeeDto.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/dto/response/DiffDto.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/entity/EmployeeHistory.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/repository/EmployeeChangeLogRepository.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/type/ModifyType.java
  src/main/java/com/codeit/sb01hrbankteam04/global/entity/BaseEntity.java
  src/main/java/com/codeit/sb01hrbankteam04/global/entity/BaseUpdatableEntity.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#19 📝 docs: README.md 파일 작성
  README.md
Labels: :memo: docs

#29 refactoring : 부서 목록 조회 시 정렬 및 페이지네이션 일관성 개선
  src/main/java/com/codeit/sb01hrbankteam04/domain/department/repository/DepartmentRepository.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/department/service/DepartmentService.java
Labels: :recycle: refactor

#28 ♻️ fix : Swagger용 직원 수정 이력 API 인터페이스 정의
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/controller/EmployeeHistoryController.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/controller/api/EmployeeHistoryApi.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/repository/EmployeeChangeLogRepository.java
  src/main/java/com/codeit/sb01hrbankteam04/global/exception/ErrorCode.java
Labels: :recycle: refactor

#31 ♻️ refactor: 부서 목록 코드 개선 및 직원 정보 수정 이력 코드 개선
  src/main/java/com/codeit/sb01hrbankteam04/domain/department/repository/DepartmentRepository.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/department/service/DepartmentService.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/controller/EmployeeHistoryController.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/controller/api/EmployeeHistoryApi.java
  src/main/java/com/codeit/sb01hrbankteam04/domain/employeehistory/repository/EmployeeChangeLogRepository.java
  src/main/java/com/codeit/sb01hrbankteam04/global/exception/ErrorCode.java
Labels: :recycle: refactor
